  
export enum BRAND_CATEGORIES {
    IT = 'IT',
    FINANCE = 'FINANCE',
    CONSTRUCTION = 'CONSTRUCTION',
    MANUFACTURING = 'MANUFACTURING',
    RESTAURANT = 'RESTAURANT',
    RETAIL = 'RETAIL',
    OTHER = 'OTHER',
}
