export enum Timezones {
    LIMA = 'America/Lima',
    NEW_YORK = 'America/New_York',
    MEXICO_CITY = 'America/Mexico_City',
    BOGOTA = 'America/Bogota',
    SANTIAGO = 'America/Santiago',
    BUENOS_AIRES = 'America/Argentina/Buenos_Aires',
    BRASILIA = 'America/Sao_Paulo',
    MADRID = 'Europe/Madrid',
    LONDON = 'Europe/London',
    PARIS = 'Europe/Paris',
    BERLIN = 'Europe/Berlin',
    TOKYO = 'Asia/Tokyo',
    SEOUL = 'Asia/Seoul',
}
